name: Lint Commit Messages

on: [pull_request]

jobs:
  commitlint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
